from __future__ import annotations

import math
from typing import Generator, Iterator, Optional

import numpy as np
import pandas as pd
from sqlalchemy import create_engine, event, MetaData, Table, Column
from sqlalchemy import Integer, String, ForeignKey, Date, text, DECIMAL
from sqlalchemy.engine import Engine

import config


engine = create_engine(
    "mssql+pyodbc://maciek_d/bank_gen"
    "?driver=ODBC+Driver+17+for+SQL+Server"
    "&Trusted_Connection=yes",
    fast_executemany=True,
    future=True,
)
metadata = MetaData()

# cf schema — cash flow schedules (generated by cf_calc_workflow)
Loan_orig_d = Table(
    "loan_orig", metadata,
    Column("schedule_id", String(8), primary_key=True, nullable=False),
    Column("bs_side", String(1), nullable=False),
    Column("rate_index", String(10), nullable=False),
    Column("fixing_dt", Date, nullable=False),
    Column("cf_start_dt", Date, primary_key=True, nullable=False),
    Column("cf_end_dt", Date, nullable=False),
    Column("cf_yf", DECIMAL(18, 6), nullable=False),
    Column("d_f", DECIMAL(18, 6), nullable=True),
    Column("fwd_rt", DECIMAL(18, 6), nullable=True),
    Column("outstanding_bal", DECIMAL(18, 2), nullable=True),
    Column("capital_pmt", DECIMAL(18, 2), nullable=True),
    Column("int_pmt", DECIMAL(18, 2), nullable=True),
    Column("total_pmt", DECIMAL(18, 2), nullable=True),
    schema="cf",
)

Loan_beh_d = Table(
    "loan_beh", metadata,
    Column("schedule_id", String(8), primary_key=True, nullable=False),
    Column("bs_side", String(1), nullable=False),
    Column("rate_index", String(10), nullable=False),
    Column("fixing_dt", Date, nullable=False),
    Column("cf_start_dt", Date, primary_key=True, nullable=False),
    Column("cf_end_dt", Date, nullable=False),
    Column("cf_yf", DECIMAL(18, 6), nullable=False),
    Column("d_f", DECIMAL(18, 6), nullable=True),
    Column("fwd_rt", DECIMAL(18, 6), nullable=True),
    Column("outstanding_bal", DECIMAL(18, 2), nullable=True),
    Column("capital_pmt", DECIMAL(18, 2), nullable=True),
    Column("prepayment_pmt", DECIMAL(18, 2), nullable=True),
    Column("int_pmt", DECIMAL(18, 2), nullable=True),
    Column("total_pmt", DECIMAL(18, 2), nullable=True),
    schema="cf",
)

Fin_inst_orig_d = Table(
    "fin_inst_orig", metadata,
    Column("schedule_id", String(8), primary_key=True, nullable=False),
    Column("bs_side", String(1), nullable=False),
    Column("rate_index", String(10), nullable=False),
    Column("fixing_dt", Date, nullable=False),
    Column("cf_start_dt", Date, primary_key=True, nullable=False),
    Column("cf_end_dt", Date, nullable=False),
    Column("cf_yf", DECIMAL(18, 6), nullable=False),
    Column("d_f", DECIMAL(18, 6), nullable=True),
    Column("fwd_rt", DECIMAL(18, 6), nullable=True),
    Column("outstanding_bal", DECIMAL(18, 2), nullable=True),
    Column("capital_pmt", DECIMAL(18, 2), nullable=True),
    Column("int_pmt", DECIMAL(18, 2), nullable=True),
    Column("total_pmt", DECIMAL(18, 2), nullable=True),
    schema="cf",
)

Fin_inst_beh_d = Table(
    "fin_inst_beh", metadata,
    Column("schedule_id", String(8), primary_key=True, nullable=False),
    Column("bs_side", String(1), nullable=False),
    Column("rate_index", String(10), nullable=False),
    Column("fixing_dt", Date, nullable=False),
    Column("cf_start_dt", Date, primary_key=True, nullable=False),
    Column("cf_end_dt", Date, nullable=False),
    Column("cf_yf", DECIMAL(18, 6), nullable=False),
    Column("d_f", DECIMAL(18, 6), nullable=True),
    Column("fwd_rt", DECIMAL(18, 6), nullable=True),
    Column("outstanding_bal", DECIMAL(18, 2), nullable=True),
    Column("capital_pmt", DECIMAL(18, 2), nullable=True),
    Column("int_pmt", DECIMAL(18, 2), nullable=True),
    Column("total_pmt", DECIMAL(18, 2), nullable=True),
    schema="cf",
)

Deposit_orig_d = Table(
    "deposit_orig", metadata,
    Column("schedule_id", String(8), primary_key=True, nullable=False),
    Column("bs_side", String(1), nullable=False),
    Column("fixing_dt", Date, nullable=False),
    Column("cf_start_dt", Date, primary_key=True, nullable=False),
    Column("cf_end_dt", Date, nullable=False),
    Column("cf_yf", DECIMAL(18, 6), nullable=False),
    Column("d_f", DECIMAL(18, 6), nullable=True),
    Column("fwd_rt", DECIMAL(18, 6), nullable=True),
    Column("outstanding_bal", DECIMAL(18, 2), nullable=True),
    Column("capital_pmt", DECIMAL(18, 2), nullable=True),
    Column("int_pmt", DECIMAL(18, 2), nullable=True),
    Column("total_pmt", DECIMAL(18, 2), nullable=True),
    schema="cf",
)

Deposit_beh_d = Table(
    "deposit_beh", metadata,
    Column("schedule_id", String(8), primary_key=True, nullable=False),
    Column("bs_side", String(1), nullable=False),
    Column("cf_start_dt", Date, primary_key=True, nullable=False),
    Column("cf_end_dt", Date, nullable=False),
    Column("cf_yf", DECIMAL(18, 6), nullable=False),
    Column("d_f", DECIMAL(18, 6), nullable=True),
    Column("fwd_rt", DECIMAL(18, 6), nullable=True),
    Column("outstanding_bal", DECIMAL(18, 2), nullable=True),
    Column("capital_pmt", DECIMAL(18, 2), nullable=True),
    Column("int_pmt", DECIMAL(18, 2), nullable=True),
    Column("total_pmt", DECIMAL(18, 2), nullable=True),
    schema="cf",
)


_CF_TABLES    = ["loan_orig", "loan_beh", "fin_inst_orig", "fin_inst_beh", "deposit_orig", "deposit_beh"]
_IRRBB_TABLES = ["liq_gap_orig", "liq_gap_beh", "ir_gap_orig", "ir_gap_beh", "ir_gap_beh_a"]


def _ensure_schemas(conn) -> None:
    for schema in ("cf", "irrbb"):
        conn.execute(text(
            f"IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = '{schema}') "
            f"EXEC('CREATE SCHEMA {schema}');"
        ))


def reset_data(mode: int, report_date=None) -> None:
    """
    mode=0 -> drop + recreate cf/irrbb tables
    mode=1 -> DELETE specific report_date data
    """
    with engine.begin() as conn:
        _ensure_schemas(conn)

        if mode == 0:
            for t in _CF_TABLES:
                conn.execute(text(f"IF OBJECT_ID('cf.{t}', 'U') IS NOT NULL DROP TABLE cf.{t};"))
            for t in _IRRBB_TABLES:
                conn.execute(text(f"IF OBJECT_ID('irrbb.{t}', 'U') IS NOT NULL DROP TABLE irrbb.{t};"))
            metadata.create_all(bind=conn, checkfirst=False)

        elif mode == 1:
            if report_date is None:
                raise ValueError("For mode=1 report_date is needed")
            for t in _CF_TABLES:
                conn.execute(text(f"DELETE FROM cf.{t} WHERE report_date = :rd"), {"rd": report_date})
            for t in _IRRBB_TABLES:
                conn.execute(text(f"DELETE FROM irrbb.{t} WHERE report_date = :rd"), {"rd": report_date})
        else:
            raise ValueError("Mode should be 0 or 1")



def sql_get_params(
    engine: Engine,
    table_name: str,
    columns: list[str],
    chunksize: int = 50_000,
    schema: str = "dbo",
) -> Iterator[pd.DataFrame]:
    where_clauses = []
    params = []

    query = f"""
    SELECT {", ".join(columns)}
    FROM {schema}.{table_name}
    """

    return pd.read_sql_query(query, engine, params=tuple(params), chunksize=chunksize)

def load_sched_params(table: str, cols: list[str], schema: str = "sched") -> Iterator[pd.DataFrame]:
    return sql_get_params(engine=engine, table_name=table, columns=cols, schema=schema)

@event.listens_for(engine, "before_cursor_execute")
def _set_fast_executemany(conn, cursor, statement, parameters, context, executemany):
    if executemany:
        cursor.fast_executemany = True


def write_df(df: pd.DataFrame, table: str, schema: str = "dbo", chunksize: int = 50_000):
    df.to_sql(
        name=table,
        con=engine,
        schema=schema,
        if_exists="append",
        index=False,
        chunksize=chunksize,
        method=None,
    )


def iter_schedule_batches(
    engine: Engine,
    table_name: str,
    batch_size: int = 1000,
    schema: str = "dbo",
) -> Generator[pd.DataFrame, None, None]:
    query = f"""
    WITH ids AS (
        SELECT DISTINCT schedule_id,
               ROW_NUMBER() OVER (ORDER BY schedule_id) AS rn
        FROM {schema}.{table_name}
    )
    SELECT s.*
    FROM {schema}.{table_name} s
    JOIN ids i ON s.schedule_id = i.schedule_id
    WHERE i.rn BETWEEN ? AND ?
    ORDER BY s.schedule_id, s.cf_start_dt
    """

    start = 1

    while True:
        df = pd.read_sql(query, engine, params=[start, start + batch_size - 1])
        if df.empty:
            break
        yield df
        start += batch_size

def sql_get_uniq_curves(tables: list[str], curve_type: str) -> pd.DataFrame:
    union_parts = []

    for table in tables:
        union_parts.append(f"""
            SELECT {curve_type} as curve_name, case when '{curve_type}'='fwd_curve' then fixing_freq
            else NULL end as fixing_freq, '{curve_type}' as curve_type
            FROM sched.{table}
            GROUP BY {curve_type}, fixing_freq
        """)

    union_sql = "\nUNION ALL\n".join(union_parts)

    query = f"""
    SELECT DISTINCT t.curve_name, t.fixing_freq, t.curve_type
    FROM (
        {union_sql}
    ) t
    """
    return pd.read_sql_query(query, engine)

def sql_select_specific_curve(curve_name: str) -> pd.DataFrame:
    query = text("""
        SELECT curve_name, n_days, year_frac, zero_rate, d_f
        FROM mkt.curves
        WHERE curve_date = :report_date
          AND curve_name = :curve_name
    """)
    return pd.read_sql_query(
        query,
        engine,
        params={"report_date": config.report_date, "curve_name": curve_name}
    )

def sql_select_fixings() -> pd.DataFrame:
    query = "SELECT * FROM mkt.fixings"
    return pd.read_sql_query(query, engine)

def sql_select_models_loan() -> pd.DataFrame:
    query = text("""
        SELECT product_code, tenor, prep_rate
        FROM bs.models_loan
        WHERE report_date = :report_date
    """)
    return pd.read_sql_query(query, engine, params={"report_date": config.report_date})


def sql_select_models_deposit() -> pd.DataFrame:
    query = text("""
        SELECT product_code, tenor, outstanding
        FROM bs.models_deposit
        WHERE report_date = :report_date
        ORDER BY product_code, tenor
    """)
    return pd.read_sql_query(query, engine, params={"report_date": config.report_date})


_TENOR_SORT = {"1D": 0, ">30Y": 362}


def _tenor_bucket(days: int) -> str:
    """Map number of days from report_date to tenor bucket label."""
    if days <= 1:
        return "1D"
    months = math.ceil(days / 30.4375)
    if months > 360:
        return ">30Y"
    return f"{months}M"


def _tenor_sort_key(label: str) -> int:
    if label in _TENOR_SORT:
        return _TENOR_SORT[label]
    return int(label[:-1])  # strip trailing 'M'


def _aggregate_gap(df: pd.DataFrame, report_date: pd.Timestamp) -> pd.DataFrame:
    """Apply sign, bucket by tenor and aggregate total payments per currency as gap_cf."""
    df = df.copy()
    sign = np.where(df["bs_side"] == "A", 1.0, -1.0)
    df["gap_cf"] = (df["capital_pmt"] + df["int_pmt"]) * sign

    # Overnight bucket = minimum cf_end_dt per currency (next business day in that currency)
    overnight_dates = df.groupby("currency")["cf_end_dt"].transform("min")
    days = (df["cf_end_dt"] - report_date).dt.days
    df["tenor_bucket"] = np.where(
        df["cf_end_dt"] == overnight_dates,
        "1D",
        days.map(_tenor_bucket),
    )

    # Aggregate payments — one row per (currency, bs_side, tenor_bucket)
    result = (
        df.groupby(["currency", "bs_side", "tenor_bucket"], sort=False)[["gap_cf"]]
        .sum()
        .reset_index()
    )

    # Compute representative cf_end_dt: overnight date from data, EOM for monthly buckets
    overnight_by_ccy = (
        df[df["tenor_bucket"] == "1D"]
        .groupby("currency")["cf_end_dt"]
        .first()
    )

    def _bucket_date(row: pd.Series) -> pd.Timestamp:
        if row["tenor_bucket"] == "1D":
            return overnight_by_ccy.get(row["currency"], pd.NaT)
        if row["tenor_bucket"] == ">30Y":
            return report_date + pd.offsets.MonthEnd(361)
        return report_date + pd.offsets.MonthEnd(int(row["tenor_bucket"][:-1]))

    result["cf_end_dt"] = result.apply(_bucket_date, axis=1)

    result["_sort"] = result["tenor_bucket"].map(_tenor_sort_key)
    result = (
        result.sort_values(["currency", "bs_side", "_sort"])
        .drop(columns="_sort")
        .reset_index(drop=True)
    )
    return result[["currency", "bs_side", "tenor_bucket", "cf_end_dt", "gap_cf"]]


def compute_liq_gap(report_date: pd.Timestamp) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Compute contractual and behavioural liquidity gap tables.

    Cash flows are placed at their contractual payment date (cf_end_dt).
    Tenor buckets: '1D' (overnight), '1M'..'360M', '>30Y'.
    Columns: currency, bs_side, tenor_bucket, cf_end_dt, gap_cf.
    """
    params = {"rd": report_date}

    orig_query = text("""
        SELECT s.bs_side, s.cf_end_dt, s.capital_pmt, s.int_pmt, i.currency
        FROM cf.loan_orig s
        JOIN sched.loans i ON s.schedule_id = i.schedule_id
        WHERE s.cf_end_dt > :rd
        UNION ALL
        SELECT s.bs_side, s.cf_end_dt, s.capital_pmt, s.int_pmt, i.currency
        FROM cf.fin_inst_orig s
        JOIN sched.fin_inst i ON s.schedule_id = i.schedule_id
        WHERE s.cf_end_dt > :rd
        UNION ALL
        SELECT s.bs_side, s.cf_end_dt, s.capital_pmt, s.int_pmt, i.currency
        FROM cf.deposit_orig s
        JOIN sched.deposits i ON s.schedule_id = i.schedule_id
        WHERE s.cf_end_dt > :rd
    """)

    beh_query = text("""
        SELECT s.bs_side, s.cf_end_dt,
               s.capital_pmt + s.prepayment_pmt AS capital_pmt,
               s.int_pmt, i.currency
        FROM cf.loan_beh s
        JOIN sched.loans i ON s.schedule_id = i.schedule_id
        WHERE s.cf_end_dt > :rd
        UNION ALL
        SELECT s.bs_side, s.cf_end_dt, s.capital_pmt, s.int_pmt, i.currency
        FROM cf.fin_inst_beh s
        JOIN sched.fin_inst i ON s.schedule_id = i.schedule_id
        WHERE s.cf_end_dt > :rd
        UNION ALL
        SELECT s.bs_side, s.cf_end_dt, s.capital_pmt, s.int_pmt, i.currency
        FROM cf.deposit_beh s
        JOIN sched.deposits i ON s.schedule_id = i.schedule_id
        WHERE s.cf_end_dt > :rd
    """)

    orig_df = pd.read_sql_query(orig_query, engine, params=params)
    beh_df  = pd.read_sql_query(beh_query,  engine, params=params)

    orig_df["cf_end_dt"] = pd.to_datetime(orig_df["cf_end_dt"])
    beh_df["cf_end_dt"]  = pd.to_datetime(beh_df["cf_end_dt"])

    return _aggregate_gap(orig_df, report_date), _aggregate_gap(beh_df, report_date)


def _aggregate_ir_gap(df: pd.DataFrame, report_date: pd.Timestamp) -> pd.DataFrame:
    """Sign, bucket by tenor and aggregate gap_cf per currency."""
    df = df.copy()
    sign = np.where(df["bs_side"] == "A", 1.0, -1.0)
    df["gap_cf"] = df["gap_cf"] * sign

    overnight_dates = df.groupby("currency")["cf_end_dt"].transform("min")
    days = (df["cf_end_dt"] - report_date).dt.days
    df["tenor_bucket"] = np.where(
        df["cf_end_dt"] == overnight_dates,
        "1D",
        days.map(_tenor_bucket),
    )

    result = (
        df.groupby(["currency", "bs_side", "tenor_bucket"], sort=False)[["gap_cf"]]
        .sum()
        .reset_index()
    )

    overnight_by_ccy = (
        df[df["tenor_bucket"] == "1D"]
        .groupby("currency")["cf_end_dt"]
        .first()
    )

    def _bucket_date(row: pd.Series) -> pd.Timestamp:
        if row["tenor_bucket"] == "1D":
            return overnight_by_ccy.get(row["currency"], pd.NaT)
        if row["tenor_bucket"] == ">30Y":
            return report_date + pd.offsets.MonthEnd(361)
        return report_date + pd.offsets.MonthEnd(int(row["tenor_bucket"][:-1]))

    result["cf_end_dt"] = result.apply(_bucket_date, axis=1)
    result["_sort"] = result["tenor_bucket"].map(_tenor_sort_key)
    result = (
        result.sort_values(["currency", "bs_side", "_sort"])
        .drop(columns="_sort")
        .reset_index(drop=True)
    )
    return result[["currency", "bs_side", "tenor_bucket", "cf_end_dt", "gap_cf"]]


def _aggregate_ir_gap_a(df: pd.DataFrame, report_date: pd.Timestamp) -> pd.DataFrame:
    """Same as _aggregate_ir_gap but keeps product_name as an additional dimension."""
    df = df.copy()
    sign = np.where(df["bs_side"] == "A", 1.0, -1.0)
    df["gap_cf"] = df["gap_cf"] * sign

    overnight_dates = df.groupby("currency")["cf_end_dt"].transform("min")
    days = (df["cf_end_dt"] - report_date).dt.days
    df["tenor_bucket"] = np.where(
        df["cf_end_dt"] == overnight_dates,
        "1D",
        days.map(_tenor_bucket),
    )

    result = (
        df.groupby(["currency", "bs_side", "product_name", "tenor_bucket"], sort=False)[["gap_cf"]]
        .sum()
        .reset_index()
    )

    overnight_by_ccy = (
        df[df["tenor_bucket"] == "1D"]
        .groupby("currency")["cf_end_dt"]
        .first()
    )

    def _bucket_date(row: pd.Series) -> pd.Timestamp:
        if row["tenor_bucket"] == "1D":
            return overnight_by_ccy.get(row["currency"], pd.NaT)
        if row["tenor_bucket"] == ">30Y":
            return report_date + pd.offsets.MonthEnd(361)
        return report_date + pd.offsets.MonthEnd(int(row["tenor_bucket"][:-1]))

    result["cf_end_dt"] = result.apply(_bucket_date, axis=1)
    result["_sort"] = result["tenor_bucket"].map(_tenor_sort_key)
    result = (
        result.sort_values(["currency", "bs_side", "product_name", "_sort"])
        .drop(columns="_sort")
        .reset_index(drop=True)
    )
    return result[["currency", "bs_side", "product_name", "tenor_bucket", "cf_end_dt", "gap_cf"]]


def compute_ir_gap(report_date: pd.Timestamp) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Compute contractual and behavioural interest rate gap (repricing gap) tables.

    Fixed rate (no fixing_dt > report_date): one row per schedule at maturity.
        gap_cf = SUM(capital_pmt) + SUM(int_pmt)

    Floating rate (has fixing_dt > report_date): multiple rows per schedule.
        - Each capital payment at its own cf_end_dt  (refinancing/reinvestment risk)
        - First int_pmt only (rn=1 by cf_end_dt)    (locked-in coupon)

    Deposits: capital + int per row (each period is its own repricing).

    Columns: currency, bs_side, tenor_bucket, cf_end_dt, gap_cf.
    """
    params = {"rd": report_date}

    _repricing_gap_cf = """
        WITH floating_scheds AS (
            SELECT schedule_id,
                   MIN(fixing_dt) AS next_fixing_dt
            FROM cf.{sched_table}
            WHERE cf_end_dt > :rd AND fixing_dt > :rd
            GROUP BY schedule_id
        ),
        base AS (
            SELECT s.schedule_id, s.cf_end_dt,
                   {capital_expr} AS capital_pmt,
                   s.int_pmt,
                   s.outstanding_bal,
                   s.fixing_dt,
                   ROW_NUMBER() OVER (PARTITION BY s.schedule_id ORDER BY s.cf_end_dt) AS rn,
                   CASE WHEN f.schedule_id IS NOT NULL THEN 1 ELSE 0 END AS is_floating,
                   f.next_fixing_dt
            FROM cf.{sched_table} s
            LEFT JOIN floating_scheds f ON s.schedule_id = f.schedule_id
            WHERE s.cf_end_dt > :rd
        ),
        float_outstanding AS (
            SELECT schedule_id, next_fixing_dt,
                   MAX(outstanding_bal) AS outstanding_at_fix
            FROM base
            WHERE is_floating = 1 AND fixing_dt = next_fixing_dt
            GROUP BY schedule_id, next_fixing_dt
        )
        SELECT i.currency, i.bs_side, b.cf_end_dt,
               b.capital_pmt + b.int_pmt AS gap_cf
        FROM base b
        JOIN sched.{id_table} i ON b.schedule_id = i.schedule_id
        WHERE b.is_floating = 0

        UNION ALL

        SELECT i.currency, i.bs_side, b.cf_end_dt,
               b.capital_pmt AS gap_cf
        FROM base b
        JOIN sched.{id_table} i ON b.schedule_id = i.schedule_id
        WHERE b.is_floating = 1 AND b.fixing_dt <= :rd

        UNION ALL

        SELECT i.currency, i.bs_side, b.cf_end_dt,
               b.int_pmt AS gap_cf
        FROM base b
        JOIN sched.{id_table} i ON b.schedule_id = i.schedule_id
        WHERE b.is_floating = 1 AND b.rn = 1

        UNION ALL

        SELECT i.currency, i.bs_side, fo.next_fixing_dt AS cf_end_dt,
               fo.outstanding_at_fix AS gap_cf
        FROM float_outstanding fo
        JOIN sched.{id_table} i ON fo.schedule_id = i.schedule_id
    """

    # Analytical template — same CTEs as _repricing_gap_cf, adds product_name to every SELECT
    _repricing_gap_cf_a = """
        WITH floating_scheds AS (
            SELECT schedule_id,
                   MIN(fixing_dt) AS next_fixing_dt
            FROM cf.{sched_table}
            WHERE cf_end_dt > :rd AND fixing_dt > :rd
            GROUP BY schedule_id
        ),
        base AS (
            SELECT s.schedule_id, s.cf_end_dt,
                   {capital_expr} AS capital_pmt,
                   s.int_pmt,
                   s.outstanding_bal,
                   s.fixing_dt,
                   ROW_NUMBER() OVER (PARTITION BY s.schedule_id ORDER BY s.cf_end_dt) AS rn,
                   CASE WHEN f.schedule_id IS NOT NULL THEN 1 ELSE 0 END AS is_floating,
                   f.next_fixing_dt
            FROM cf.{sched_table} s
            LEFT JOIN floating_scheds f ON s.schedule_id = f.schedule_id
            WHERE s.cf_end_dt > :rd
        ),
        float_outstanding AS (
            SELECT schedule_id, next_fixing_dt,
                   MAX(outstanding_bal) AS outstanding_at_fix
            FROM base
            WHERE is_floating = 1 AND fixing_dt = next_fixing_dt
            GROUP BY schedule_id, next_fixing_dt
        )
        SELECT i.currency, i.bs_side, b.cf_end_dt,
               b.capital_pmt + b.int_pmt AS gap_cf,
               {product_name_expr} AS product_name
        FROM base b
        JOIN sched.{id_table} i ON b.schedule_id = i.schedule_id
        WHERE b.is_floating = 0

        UNION ALL

        SELECT i.currency, i.bs_side, b.cf_end_dt,
               b.capital_pmt AS gap_cf,
               {product_name_expr} AS product_name
        FROM base b
        JOIN sched.{id_table} i ON b.schedule_id = i.schedule_id
        WHERE b.is_floating = 1 AND b.fixing_dt <= :rd

        UNION ALL

        SELECT i.currency, i.bs_side, b.cf_end_dt,
               b.int_pmt AS gap_cf,
               {product_name_expr} AS product_name
        FROM base b
        JOIN sched.{id_table} i ON b.schedule_id = i.schedule_id
        WHERE b.is_floating = 1 AND b.rn = 1

        UNION ALL

        SELECT i.currency, i.bs_side, fo.next_fixing_dt AS cf_end_dt,
               fo.outstanding_at_fix AS gap_cf,
               {product_name_expr} AS product_name
        FROM float_outstanding fo
        JOIN sched.{id_table} i ON fo.schedule_id = i.schedule_id
    """

    loans_orig_q    = text(_repricing_gap_cf.format(
        capital_expr="s.capital_pmt",                    sched_table="loan_orig",     id_table="loans"))
    fin_inst_orig_q = text(_repricing_gap_cf.format(
        capital_expr="s.capital_pmt",                    sched_table="fin_inst_orig", id_table="fin_inst"))
    loans_beh_q     = text(_repricing_gap_cf.format(
        capital_expr="s.capital_pmt + s.prepayment_pmt", sched_table="loan_beh",      id_table="loans"))
    fin_inst_beh_q  = text(_repricing_gap_cf.format(
        capital_expr="s.capital_pmt",                    sched_table="fin_inst_beh",  id_table="fin_inst"))

    loans_beh_a_q    = text(_repricing_gap_cf_a.format(
        capital_expr="s.capital_pmt + s.prepayment_pmt", sched_table="loan_beh",     id_table="loans",
        product_name_expr="i.product_code"))
    fin_inst_beh_a_q = text(_repricing_gap_cf_a.format(
        capital_expr="s.capital_pmt",                    sched_table="fin_inst_beh", id_table="fin_inst",
        product_name_expr="CAST(i.product_code AS NVARCHAR)"))

    depo_orig_q = text("""
        SELECT i.currency, s.bs_side, s.cf_end_dt,
               s.capital_pmt + s.int_pmt AS gap_cf
        FROM cf.deposit_orig s
        JOIN sched.deposits i ON s.schedule_id = i.schedule_id
        WHERE s.cf_end_dt > :rd
    """)

    depo_beh_q = text("""
        SELECT i.currency, s.bs_side, s.cf_end_dt,
               s.capital_pmt + s.int_pmt AS gap_cf
        FROM cf.deposit_beh s
        JOIN sched.deposits i ON s.schedule_id = i.schedule_id
        WHERE s.cf_end_dt > :rd
    """)

    depo_beh_a_q = text("""
        SELECT i.currency, s.bs_side, s.cf_end_dt,
               s.capital_pmt + s.int_pmt AS gap_cf,
               i.product_code AS product_name
        FROM cf.deposit_beh s
        JOIN sched.deposits i ON s.schedule_id = i.schedule_id
        WHERE s.cf_end_dt > :rd
    """)

    def _fetch(q) -> pd.DataFrame:
        df = pd.read_sql_query(q, engine, params=params)
        df["cf_end_dt"] = pd.to_datetime(df["cf_end_dt"])
        return df

    orig_df = pd.concat(
        [_fetch(loans_orig_q), _fetch(fin_inst_orig_q), _fetch(depo_orig_q)],
        ignore_index=True,
    )
    beh_df = pd.concat(
        [_fetch(loans_beh_q), _fetch(fin_inst_beh_q), _fetch(depo_beh_q)],
        ignore_index=True,
    )
    beh_a_df = pd.concat(
        [_fetch(loans_beh_a_q), _fetch(fin_inst_beh_a_q), _fetch(depo_beh_a_q)],
        ignore_index=True,
    )

    return (
        _aggregate_ir_gap(orig_df, report_date),
        _aggregate_ir_gap(beh_df, report_date),
        _aggregate_ir_gap_a(beh_a_df, report_date),
    )
